---
- name: Attach policy to S3 bucket
  hosts: localhost
  tasks:
    - name: Read Terraform output
      command: cat tf_output.json
      register: tf_output

    - name: Parse Terraform output
      set_fact:
        bucket_name: "{{ tf_output.stdout | from_json | json_query('bucket_name.value') }}"

    - name: Attach S3 bucket policy
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        policy: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::{{ bucket_name }}/*"
              }
            ]
          }
        state: present
